from pathlib import Path

import pandas as pd

from rdflib import (
    Graph,
    Literal,
    Namespace,
    RDF,
    URIRef,
    XSD,
)


# ---------------------------------------------------------
# Project paths
# ---------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parent.parent

ONTOLOGY_FILE = (
    PROJECT_ROOT
    / "ontology"
    / "learner_support.ttl"
)

INPUT_FILE = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "learner_semantic_states_BBB_2014J_day60.csv"
)

GRAPH_OUTPUT_DIR = (
    PROJECT_ROOT
    / "outputs"
    / "graphs"
)

GRAPH_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

GRAPH_OUTPUT_FILE = (
    GRAPH_OUTPUT_DIR
    / "learner_graph_BBB_2014J_day60.ttl"
)


# ---------------------------------------------------------
# Experiment configuration
# ---------------------------------------------------------

CODE_MODULE = "BBB"
CODE_PRESENTATION = "2014J"
CUTOFF_DAY = 60


# ---------------------------------------------------------
# Namespace
# ---------------------------------------------------------

LS = Namespace(
    "http://example.org/learner-support/"
)


# ---------------------------------------------------------
# Helper: safe numeric literal
# ---------------------------------------------------------

def add_numeric_literal(
    graph,
    subject,
    predicate,
    value,
    datatype=XSD.decimal,
):
    """
    Add a numeric RDF literal only when the value is present.

    Missing data is not converted to zero because:

        missing evidence != zero value
    """

    if pd.isna(value):
        return

    if datatype == XSD.integer:

        graph.add(
            (
                subject,
                predicate,
                Literal(
                    int(value),
                    datatype=XSD.integer,
                ),
            )
        )

    else:

        graph.add(
            (
                subject,
                predicate,
                Literal(
                    float(value),
                    datatype=datatype,
                ),
            )
        )


# ---------------------------------------------------------
# Load ontology
# ---------------------------------------------------------

def load_ontology():
    """
    Load the Turtle ontology into an RDFLib graph.
    """

    if not ONTOLOGY_FILE.exists():

        raise FileNotFoundError(
            f"Ontology not found:\n"
            f"{ONTOLOGY_FILE}"
        )

    graph = Graph()

    graph.parse(
        ONTOLOGY_FILE,
        format="turtle",
    )

    graph.bind(
        "ls",
        LS,
    )

    return graph


# ---------------------------------------------------------
# Load learner semantic states
# ---------------------------------------------------------

def load_semantic_states():
    """
    Load learner semantic-state data generated by
    src/ontology.py.
    """

    if not INPUT_FILE.exists():

        raise FileNotFoundError(
            f"Semantic-state dataset not found:\n"
            f"{INPUT_FILE}\n\n"
            f"Run:\n"
            f"python -m src.ontology"
        )

    return pd.read_csv(
        INPUT_FILE
    )


# ---------------------------------------------------------
# Create learner knowledge graph
# ---------------------------------------------------------

def build_knowledge_graph(
    graph,
    learner_states,
):
    """
    Create RDF learner and observation instances.

    One learner has one Day-60 observation in this
    experiment.
    """

    module_presentation = LS[
        f"ModulePresentation_"
        f"{CODE_MODULE}_"
        f"{CODE_PRESENTATION}"
    ]

    graph.add(
        (
            module_presentation,
            RDF.type,
            LS.ModulePresentation,
        )
    )

    for _, row in learner_states.iterrows():

        student_id = int(
            row["id_student"]
        )

        learner = LS[
            f"Learner_{student_id}"
        ]

        observation = LS[
            f"Observation_"
            f"{student_id}_"
            f"D{CUTOFF_DAY}"
        ]

        # -------------------------------------------------
        # Core learner triples
        # -------------------------------------------------

        graph.add(
            (
                learner,
                RDF.type,
                LS.Learner,
            )
        )

        graph.add(
            (
                learner,
                LS.enrolledIn,
                module_presentation,
            )
        )

        graph.add(
            (
                learner,
                LS.hasObservation,
                observation,
            )
        )

        # -------------------------------------------------
        # Observation
        # -------------------------------------------------

        graph.add(
            (
                observation,
                RDF.type,
                LS.Observation,
            )
        )

        graph.add(
            (
                observation,
                LS.observedAtDay,
                Literal(
                    CUTOFF_DAY,
                    datatype=XSD.integer,
                ),
            )
        )

        # -------------------------------------------------
        # Semantic states
        # -------------------------------------------------

        graph.add(
            (
                observation,
                LS.hasPerformanceState,
                LS[
                    row[
                        "performance_state"
                    ]
                ],
            )
        )

        graph.add(
            (
                observation,
                LS.hasAssessmentTrendState,
                LS[
                    row[
                        "assessment_trend_state"
                    ]
                ],
            )
        )

        graph.add(
            (
                observation,
                LS.hasEngagementState,
                LS[
                    row[
                        "engagement_state"
                    ]
                ],
            )
        )

        graph.add(
            (
                observation,
                LS.hasInactivityState,
                LS[
                    row[
                        "inactivity_state"
                    ]
                ],
            )
        )

        graph.add(
            (
                observation,
                LS.hasCompletionState,
                LS[
                    row[
                        "completion_state"
                    ]
                ],
            )
        )

        graph.add(
            (
                observation,
                LS.hasSubmissionState,
                LS[
                    row[
                        "submission_state"
                    ]
                ],
            )
        )

        graph.add(
            (
                observation,
                LS.hasEvidenceSufficiency,
                LS[
                    row[
                        "evidence_sufficiency"
                    ]
                ],
            )
        )

        # -------------------------------------------------
        # Numerical evidence
        # -------------------------------------------------

        add_numeric_literal(
            graph,
            observation,
            LS.weightedAssessmentAverage,
            row[
                "weighted_assessment_average"
            ],
        )

        add_numeric_literal(
            graph,
            observation,
            LS.assessmentTrend,
            row[
                "assessment_trend"
            ],
        )

        add_numeric_literal(
            graph,
            observation,
            LS.recentClicks,
            row[
                "recent_14_day_clicks"
            ],
            datatype=XSD.integer,
        )

        add_numeric_literal(
            graph,
            observation,
            LS.previousClicks,
            row[
                "previous_14_day_clicks"
            ],
            datatype=XSD.integer,
        )

        add_numeric_literal(
            graph,
            observation,
            LS.engagementChange,
            row[
                "engagement_change"
            ],
        )

        add_numeric_literal(
            graph,
            observation,
            LS.daysSinceLastActivity,
            row[
                "days_since_last_activity"
            ],
            datatype=XSD.integer,
        )

        add_numeric_literal(
            graph,
            observation,
            LS.assessmentCompletionRate,
            row[
                "assessment_completion_rate"
            ],
        )

        add_numeric_literal(
            graph,
            observation,
            LS.lateSubmissions,
            row[
                "late_submissions"
            ],
            datatype=XSD.integer,
        )

    return graph


# ---------------------------------------------------------
# Validate graph
# ---------------------------------------------------------

def validate_graph(
    graph,
    expected_learners,
):
    """
    Validate learner and observation counts.
    """

    learner_query = """
    PREFIX ls: <http://example.org/learner-support/>

    SELECT (COUNT(?learner) AS ?count)
    WHERE {
        ?learner a ls:Learner .
    }
    """

    observation_query = """
    PREFIX ls: <http://example.org/learner-support/>

    SELECT (COUNT(?observation) AS ?count)
    WHERE {
        ?observation a ls:Observation .
    }
    """

    learner_result = list(
        graph.query(
            learner_query
        )
    )

    observation_result = list(
        graph.query(
            observation_query
        )
    )

    learner_count = int(
        learner_result[0][0]
    )

    observation_count = int(
        observation_result[0][0]
    )

    print(
        "\n"
        + "=" * 70
    )

    print(
        "KNOWLEDGE GRAPH VALIDATION"
    )

    print(
        "=" * 70
    )

    print(
        f"Expected learners: "
        f"{expected_learners:,}"
    )

    print(
        f"RDF learners: "
        f"{learner_count:,}"
    )

    print(
        f"RDF observations: "
        f"{observation_count:,}"
    )

    print(
        f"Total RDF triples: "
        f"{len(graph):,}"
    )

    if (
        learner_count
        == expected_learners
        and observation_count
        == expected_learners
    ):

        print(
            "\nGraph validation: PASS"
        )

    else:

        print(
            "\nGraph validation: FAIL"
        )


# ---------------------------------------------------------
# Example SPARQL query
# ---------------------------------------------------------

def query_highly_inactive(
    graph,
    limit=10,
):
    """
    Find learners whose Day-60 observation is classified
    as HighlyInactive.
    """

    query = f"""
    PREFIX ls: <http://example.org/learner-support/>

    SELECT ?learner ?observation ?daysInactive
    WHERE {{

        ?learner
            a ls:Learner ;
            ls:hasObservation ?observation .

        ?observation
            ls:hasInactivityState
                ls:HighlyInactive ;
            ls:daysSinceLastActivity
                ?daysInactive .
    }}
    LIMIT {limit}
    """

    results = graph.query(
        query
    )

    print(
        "\n"
        + "=" * 70
    )

    print(
        "EXAMPLE SPARQL QUERY"
    )

    print(
        "Highly inactive learners"
    )

    print(
        "=" * 70
    )

    for row in results:

        learner_name = (
            str(
                row.learner
            )
            .split("/")[-1]
        )

        observation_name = (
            str(
                row.observation
            )
            .split("/")[-1]
        )

        print(
            f"{learner_name:<25} "
            f"{observation_name:<35} "
            f"days inactive = "
            f"{row.daysInactive}"
        )


# ---------------------------------------------------------
# Print one learner graph
# ---------------------------------------------------------

def print_example_learner(
    graph,
    learner_id,
):
    """
    Print RDF triples associated with one learner and their
    Day-60 observation.
    """

    learner = LS[
        f"Learner_{learner_id}"
    ]

    observation = LS[
        f"Observation_"
        f"{learner_id}_"
        f"D{CUTOFF_DAY}"
    ]

    print(
        "\n"
        + "=" * 70
    )

    print(
        f"EXAMPLE RDF GRAPH: "
        f"LEARNER {learner_id}"
    )

    print(
        "=" * 70
    )

    for predicate, obj in graph.predicate_objects(
        learner
    ):

        print(
            f"{learner.n3(graph.namespace_manager)} "
            f"{predicate.n3(graph.namespace_manager)} "
            f"{obj.n3(graph.namespace_manager)}"
        )

    print()

    for predicate, obj in graph.predicate_objects(
        observation
    ):

        print(
            f"{observation.n3(graph.namespace_manager)} "
            f"{predicate.n3(graph.namespace_manager)} "
            f"{obj.n3(graph.namespace_manager)}"
        )


# ---------------------------------------------------------
# Save graph
# ---------------------------------------------------------

def save_graph(
    graph,
):
    """
    Serialize RDF graph as Turtle.
    """

    graph.serialize(
        destination=str(
            GRAPH_OUTPUT_FILE
        ),
        format="turtle",
    )

    print(
        "\nSaved RDF knowledge graph:"
    )

    print(
        GRAPH_OUTPUT_FILE
    )


# ---------------------------------------------------------
# Main
# ---------------------------------------------------------

if __name__ == "__main__":

    print(
        "\nBuilding learner RDF knowledge graph..."
    )

    # -----------------------------------------------------
    # 1. Load ontology schema
    # -----------------------------------------------------

    graph = load_ontology()

    ontology_triples = len(
        graph
    )

    print(
        f"Ontology triples loaded: "
        f"{ontology_triples:,}"
    )

    # -----------------------------------------------------
    # 2. Load semantic learner states
    # -----------------------------------------------------

    learner_states = (
        load_semantic_states()
    )

    print(
        f"Learner states loaded: "
        f"{len(learner_states):,}"
    )

    # -----------------------------------------------------
    # 3. Generate RDF instances
    # -----------------------------------------------------

    graph = build_knowledge_graph(
        graph,
        learner_states,
    )

    # -----------------------------------------------------
    # 4. Validate
    # -----------------------------------------------------

    validate_graph(
        graph,
        expected_learners=len(
            learner_states
        ),
    )

    # -----------------------------------------------------
    # 5. Print example learner
    # -----------------------------------------------------

    example_student = int(
        learner_states.iloc[0][
            "id_student"
        ]
    )

    print_example_learner(
        graph,
        example_student,
    )

    # -----------------------------------------------------
    # 6. Run example SPARQL query
    # -----------------------------------------------------

    query_highly_inactive(
        graph,
        limit=10,
    )

    # -----------------------------------------------------
    # 7. Save RDF graph
    # -----------------------------------------------------

    save_graph(
        graph
    )

    print(
        "\n"
        + "=" * 70
    )

    print(
        "KNOWLEDGE GRAPH GENERATION COMPLETE"
    )

    print(
        "=" * 70
    )